# build environment
FROM node:lts as build
WORKDIR /app

COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent
RUN npm install react-scripts@5.0.1 -g --silent
RUN npm i
COPY . ./
RUN npm run build

RUN npm build -o /client

# production environment
FROM nginx:stable-alpine

WORKDIR /

COPY --from=build /client /client
# new
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
ENTRYPOINT [ "/client" ]

# # build environment
# FROM node:lts as build
# WORKDIR /app
# ENV PATH /app/node_modules/.bin:$PATH
# COPY package.json ./
# COPY package-lock.json ./
# RUN npm ci --silent
# RUN npm install react-scripts@5.0.1 -g --silent
# RUN npm i
# COPY . ./
# RUN npm run build

# # production environment
# FROM nginx:stable-alpine
# COPY --from=build /app/build /usr/share/nginx/html
# # new
# COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
# ENTRYPOINT [ "/client" ]